<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>  
    <groupId>org.exampleapps.greatbig</groupId>
    <artifactId>sbom-example</artifactId>
    <version>0.0.0</version>
    <packaging>jar</packaging>
    <name>SBOM Example</name>

    <properties>
       <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <cyclonedx.maven.plugin.version>2.0.3</cyclonedx.maven.plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
    <groupId>ch.sbb.polarion.extensions</groupId>
    <artifactId>ch.sbb.polarion.extension.generic.app</artifactId>
    <version>8.0.0</version>
</dependency>
        <dependency>
    <groupId>ch.sbb.polarion.extensions</groupId>
    <artifactId>ch.sbb.polarion.extension.diff-tool</artifactId>
    <version>5.0.0</version>
</dependency>
	    <dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-docgen</artifactId>
    <version>3.5.1</version>
</dependency>


        
    </dependencies>
    <build>
       <plugins>
            <!-- CycloneDX Maven Plugin to generate SBOM -->
            <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                <version>${cyclonedx.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>makeBom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

   
</project>
