<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>  
    <groupId>org.exampleapps.greatbig</groupId>
    <artifactId>great-big-example-application</artifactId>
    <version>0.0.0</version>
    <packaging>war</packaging>
    <name>Great Big Example Application</name>

    <properties>
       <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <cyclonedx.maven.plugin.version>2.0.3</cyclonedx.maven.plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
    <groupId>io.github.jhipster</groupId>
    <artifactId>jhipster-framework</artifactId>
    <version>3.9.1</version>
</dependency>
        <dependency>
    <groupId>io.dropwizard.metrics</groupId>
    <artifactId>metrics-logback15</artifactId>
    <version>4.2.30</version>
</dependency>
        
    </dependencies>
    <build>
       <plugins>
            <!-- CycloneDX Maven Plugin to generate SBOM -->
            <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                <version>${cyclonedx.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>makeBom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

   
</project>
